project:
  type: website
  resources:
    - cv.pdf
  preview:
    port: 7777
  output-dir: docs

website:
  title: "Saurabh Band"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: ./papers/papers.qmd
        text: Publications
      - href: ./cv/cv.qmd
        text: CV
      - href: ./projects/projects.qmd
        text: Projects
      - href: ./extras/extras.qmd
        text: More

  page-footer:
    left: "© 2025 Saurabh Band"

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true



