---
title: "Publications"
bibliography: references.bib
# bibliographystyle: ieee
# citeproc: true
# nocite: |
#   @*


---


<!-- ## 2024 -->

S. Band et al., “Reliability Analysis of a Monitoring System for Extraterrestrial Habitats,” in 2024 20th International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob), Oct. 2024, pp. 331–338. <a href="https://ieeexplore.ieee.org/document/10770488" target="_blank">doi: 10.1109/WiMob61911.2024.10770488</a>.

S. Band and A. Foerster, “(POSTER) Navigating the Unknown: Anomaly Detection in Sensor Nodes Based on Event Traces,” in 2024 20th International Conference on Distributed Computing in Smart Systems and the Internet of Things (DCOSS-IoT), Apr. 2024, pp. 756–758. <a href="https://ieeexplore.ieee.org/document/10621503" target="_blank">doi: 10.1109/DCOSS-IoT61029.2024.00115</a>.

<!-- ## 2023 -->

S. Band et al., “Reliability Analysis of Monitoring System for Extraterrestrial Habitat using CTMC and Empirical Evaluation,” May 14, 2023, arXiv: arXiv:2305.08143. <a href="https://arxiv.org/abs/2305.08143" target="_blank">doi: 10.48550/arXiv.2305.08143</a>.

S. Attarha, S. Band, and A. Förster, Automated Fault Detection Framework for Reliable Provision of IoT Applications in Agriculture. 2023, p. 8. <a href="https://ieeexplore.ieee.org/document/10108238" target="_blank">doi: 10.1109/DRCN57075.2023.10108238</a>.

P. Große Maestrup et al., “Integration of a Photobioreactor into the MaMBA Facility as Part of a Human-centered Life Support System,” Jul. 2023, Accessed: Sep. 08, 2025. [Online]. Available:  <a href="https://hdl.handle.net/2346/94682" target="_blank">https://hdl.handle.net/2346/94682</a> 


<!-- ::: {#refs}
::: -->

